import "./globals.css";
import { Inter } from "next/font/google";
import Sidebar from "./../components/Sidebar";
import { BsArrowLeftShort } from "react-icons/bs";

import MenuContextProvider from "@/context/MenuContext";
import MainContent from "@/components/MainContent";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex overflow-hidden">
        <div className="bg-gray-100 flex flex-row">
          <MenuContextProvider>
            <Sidebar />
            <MainContent>{children}</MainContent>
          </MenuContextProvider>
        </div>
      </body>
    </html>
  );
}
